### ISSUE TITLE
Photobar == null

### ISSUE THREAD

**Issue by Swader** [danigrant/nft-twitter-ext#2]
Fresh install, photobar is null it seems.

![image](https://user-images.githubusercontent.com/1430603/63644991-7b558480-c6f5-11e9-9f60-21f5d706aa61.png)

**Comment by danigrant** [comment]
I will fix, thanks!

**Comment by danigrant** [comment]
This should be fixed in the new version

**Comment by Swader** [comment]
When is the new version getting released? Still broken for me at 0.1112
